traefik:
  service:
    type: ClusterIP

controller:
  image:
    name: ghcr.io/dask/dask-gateway-server
    tag: 2023.1.1

gateway:
  image:
    name: ghcr.io/dask/dask-gateway-server
    tag: 2023.1.1
  env:
  - name: IDLE_TIMEOUT
    value: "60"
  extraConfig:
    # Note that the key name here doesn't matter. Values in the
    # `extraConfig` map are concatenated, sorted by key name.
    clusteroptions: |
      import os
      idle_timeout =  int(os.environ.get("IDLE_TIMEOUT", 500))
      print("JJJJJJJJJJJJJJJ", idle_timeout, flush=True)
      c.KubeClusterConfig.idle_timeout = idle_timeout
#         from dask_gateway_server.options import Options, Integer, Float, String

#         def option_handler(options):
#             return {
#                 "worker_cores": options.worker_cores,
#                 "worker_memory": "%fG" % options.worker_memory,
#                 "image": options.image,
#             }

#         c.Backend.cluster_options = Options(
#             Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
#             Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
#             String("image", default="daskgateway/dask-gateway:latest", label="Image"),
#             handler=option_handler,
#         )

